Count Grapheme Clusters (Emojis) once when calculating string length
FluentValidation/FluentValidation pull request #1924
Opened 2022-04-11 16:57 UTC by CooperWolfe

see Fixes #1923

2022-04-11 17:25 UTC, CooperWolfe commented
Snuck into this PR is adding dotnet 6 to the target frameworks, which was necessary for me to run my tests on a machine without dotnet 5 runtime

2022-04-12 16:25 UTC, JeremySkinner requested changes
Hi @CooperWolfe thanks so much for this! A couple of minor changes that i've commented on:

- Please ensure you match the project coding style for consistency (braces layout)
- Please can you revert the net6 targets that were added? It's best to keep PRs focused on a single issue. Feel free to add a separate PR for this, or otherwise I'll do it at some point as part of the 11.x branch.

Thanks!

2022-04-12 16:25 UTC, JeremySkinner commented on src/FluentValidation.Tests/ExactLengthValidatorTester.cs
> +		{
Please could move the opening brace be on the end of the preceding line ([as per our coding standard](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#contributing-code-and-content))? Thanks!

2022-04-12 16:25 UTC, JeremySkinner commented on src/FluentValidation.Tests/FluentValidation.Tests.csproj
> +    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
Please can you remove this? This is already being handled as part of the 11.0 upgrade, and it's preferred that PRs focus on one specific change only.

2022-04-12 16:25 UTC, JeremySkinner commented on src/FluentValidation.Tests/LengthValidatorTests.cs
> +		{
Brace layout again please

2022-04-12 16:25 UTC, JeremySkinner commented on src/FluentValidation.Tests/StringEnumValidatorTests.cs
> +#if NETCOREAPP3_1 || NET5_0 || NET6_0
Please can this be reverted

2022-04-12 16:31 UTC, JeremySkinner commented
I'm also wondering whether this should be an opt-in behaviour, as technically this is a runtime breaking change. Let me have a think about this and will get back to you.

2022-04-12 16:37 UTC, CooperWolfe commented
Sure. Admittedly I had the same thought. Another validator entirely feels like overkill. A boolean flag feels shortsighted. A system-wide option feels inflexible. Maybe we introduce an overload using a configuration class? Something like:
```csharp
RuleFor(x => x.Content).Length(2, opt => opt.UseLengthInTextElements = true);
```

2022-04-13 08:00 UTC, JeremySkinner commented
I think a configuration object like that is probably overkill, I'd be tempted to go with an optional parameter for now (via a second overload of all of the `*Length` related methods). Although I am starting to wonder if it's easier to just point end users to using a custom rule with `Must` if they need to do this.

2022-04-14 19:13 UTC, CooperWolfe commented
That's fine, I suppose we can close this then

2022-04-14 19:13 UTC, closed without merging