Restore linking between chaildren and parent contexts
FluentValidation/FluentValidation pull request #1945
Opened 2022-05-24 17:58 UTC by guffy1234

Hi

As I told you in #1942 it would be nice to just restore the link between parent context and children contexts. This will allow to creation of custom root contexts and traverse to root from any child validator. Otherwise, the existence of ParentContext property is just senseless.
As you said it's a volunteer project, so I trying to help you with MR. :)
I removed the obsolete boolean property and change the code to propagate _parent value by default.

2022-05-24 17:58 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1945) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1945) before we can accept your contribution.<br/><br/>:x: guffy1234 [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1945)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1945) it.</sub>

2022-05-24 19:45 UTC, JeremySkinner commented on src/FluentValidation/IValidationContext.cs
> -		public ValidationContext<TChild> CloneForChildValidator<TChild>(TChild instanceToValidate, bool preserveParentContext = false, IValidatorSelector selector = null) {
This is a breaking change to the public API. The caller should be updated to pass `true` rather than changing this method.

2022-05-24 19:49 UTC, JeremySkinner requested changes
Thanks for this, I need to do some testing to make sure there are no unexpected side affects of doing this, but in principle I think this should be fine. A few changes that'll be needed though:

- Changing the method signature of `CloneForChildValidator` is a breaking change, which should be avoided outside of major version releases. This change should be reverted as it's breaking the build. 
- The calling method (`ChildValidatorAdaptor.CreateNewValidationContextForChildValidator`) should be updated to pass `true` as the second argument rather than removing the argument entirely.
- Please make sure you sign the CLA too or we won't be able to accept the PR 

Thanks for wanting to be involved!

2022-05-24 21:11 UTC, JeremySkinner approved these changes

2022-05-24 21:20 UTC, merged

2022-05-24 21:24 UTC, JeremySkinner commented
Merged, thanks. I'll aim to push out a release on Friday.

2022-05-27 09:45 UTC, JeremySkinner commented
Released in 11.0.2