StringEnumValidator, cache enum names
FluentValidation/FluentValidation pull request #2229
Opened 2024-07-06 19:49 UTC by Xyzzyall

This will prevent unnecessary assembly scans and allocations in `StringEnumValidator.IsValid`. 

Check the source code of `Enum.GetNames` to understand the reasons of this change.

2024-07-06 19:51 UTC, Xyzzyall commented
@dotnet-policy-service agree

2024-07-06 19:56 UTC, Xyzzyall commented
Maybe there are reasons I don't know why `Enum.GetNames` should be used on every validation, which btw could be many on a high load.

If there is any, I wish to see some comments straight in source code on why this should be called on every validation.

2024-07-07 17:29 UTC, JeremySkinner requested changes
hi @Xyzzyall this doesn't build. 

Line 39 is trying to reference a field that's been removed. It should be `_enumNames = Enum.GetNames(enumType);`

Please can you correct this, and then I'll merge it in.

2024-07-16 10:18 UTC, JeremySkinner approved these changes

2024-07-16 10:51 UTC, merged

2024-07-16 10:51 UTC, JeremySkinner commented
thanks!